CONFIG = {
    "data": {
        "train_dir": "./base_training_6/train",
        "val_dir": "./base_training_6/validation",
        "test_dir": "./base_training_6/test",
        "image_size": (224, 224),
        "max_frames": 32,
        "min_frames_per_stage": 8,
        "num_stages": 4,
        "batch_size": 4,
        "num_workers": 0,
        "pin_memory": False,
        "shuffle_train": True,
        "normalize_mean": [0.485, 0.456, 0.406],
        "normalize_std": [0.229, 0.224, 0.225],
        "augmentation": {
            "random_rotation": 10,
            "random_horizontal_flip": 0.3,
            "random_vertical_flip": 0.2,
        },
    },
    "model": {
        "num_classes": 6,
        "hidden_size": 128,
        "dropout_rate": 0.4,
        "temporal_aggregation": "cfc",
        "pretrained": True,
        "label_smoothing": 0.0,
        "use_label_guidance_for_temporal": False,
        "enable_inter_stage_transfer": True,
        "enable_cross_stage_modeling": True,
        "enable_continuous_dynamics": True,
        "enable_hidden_state_transfer": True,
        "cfc_mode": "cfc",
        "cfc_units": 64,
        "cfc_proj_size": 32,
        "cfc_return_sequences": True,
        "cfc_mixed_memory": True,
        "cfc_no_gate": False,
        "cfc_minimal": False,
        "ltc_ode_unfolds": 8,
        "ltc_epsilon": 1e-8,
    },
    "training": {
        "num_epochs": 100,
        "learning_rate": 1e-4,
        "weight_decay": 2e-4,
        "scheduler_step_size": 25,
        "scheduler_gamma": 0.1,
        "warmup_epochs": 8,
        "gradient_clip_norm": 0.3,
        "gradient_accumulation_steps": 8,
        "use_gradient_checkpointing": False,
        "use_mixup": False,
        "mixup_alpha": 0.1,
        "early_stopping": {
            "patience": 8,
            "min_delta": 0.0005,
            "restore_best_weights": True,
        },
        "scheduler_type": "cosine",
        "cosine_t_max": 60,
        "plateau_factor": 0.3,
        "plateau_patience": 10,
    },
    "distillation": {
        "enabled": False,
        "alpha": 0.3,
        "feature_alpha": 0.1,
        "feature_loss_type": "cosine",
        "use_feature_distillation": False,
        "use_logits_distillation": True,
        "logits_alpha": 0.2,
        "temperature": 3.0,
        "adaptive_alpha": False,
        "warmup_epochs": 8,
        "detailed_analysis": {
            "enabled": True,
            "show_stage_differences": True,
            "show_feature_statistics": True,
            "show_convergence_trends": True,
            "analysis_interval": 1,
            "save_detailed_logs": True,
        },
    },
    "system": {
        "device": "cuda:0",
        "mixed_precision": True,
        "gpu_rest_interval": 10,
        "gpu_rest_duration": 180,
        "tensorboard_log_interval": 3,
    },
    "paths": {"teacher_model_path": "./teacher_model_checkpoints/best_teacher_model.pth"},
}

